### ISSUE TITLE
java.lang.NullPointerException when running TestRig

### ISSUE THREAD

**Issue by baruchl** [tunnelvisionlabs/antlrworks2#48]
Hello,
I'm using antlrworks2 version 2.1.
When I try to run testrig on any grammar file and input file, I get the following exception in the notification window, and from there I cannot recover:

java.lang.NullPointerException
	at org.antlr.works.editor.grammar.actions.RunInTestRigAction$TestRigTask.run(RunInTestRigAction.java:295)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1432)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2042)

Attached is the grammar and input file I'm using, please note it happens all the time for any file.
![math_eample](https://cloud.githubusercontent.com/assets/3430307/6822225/cb5c5948-d2e6-11e4-8edb-b3d820c9fb73.png) --> change the file extension to .txt

![calculator](https://cloud.githubusercontent.com/assets/3430307/6822250/efd3b4ec-d2e6-11e4-89e7-6d55082dcfa3.png) --> change the file extension to .g

Appreciate any help.
Busi

**Comment by baruchl** [comment]
Additional system info for debug:
Java: 1.7.0_76; Java HotSpot(TM) 64-Bit Server VM 24.76-b04
Runtime: Java(TM) SE Runtime Environment 1.7.0_76-b36
System: Windows 8 version 6.2 running on amd64; Cp1255; en_US (antlrworks2)

**Comment by baruchl** [comment]
Update: When I downloaded JDK 8U40 it worked!
this is the new system info:
Java: 1.8.0_40; Java HotSpot(TM) 64-Bit Server VM 25.40-b25
Runtime: Java(TM) SE Runtime Environment 1.8.0_40-b26

I'm leaving the issue opened for 1.7.

**Comment by pete-w** [comment]
Same stack trace with the following system:

Product Version: ANTLRWorks 2 20130716-5d2e7d936ca1
Java: 1.8.0_51; Java HotSpot(TM) 64-Bit Server VM 25.51-b03
Runtime: Java(TM) SE Runtime Environment 1.8.0_51-b16
System: Windows 7 version 6.1 running on amd64; Cp1252; en_NZ (antlrworks2)
